# Generated by Django 3.1.7 on 2021-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Hotel_name', models.CharField(max_length=250)),
                ('room_type', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('indate', models.CharField(max_length=250)),
                ('outdate', models.CharField(max_length=250)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(max_length=250)),
                ('payment', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fconfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('bill', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=250)),
                ('departure', models.CharField(max_length=250)),
                ('arrival', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('inclusions', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('no_of_days', models.CharField(max_length=250)),
                ('payment', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=250)),
                ('review', models.CharField(max_length=300)),
                ('stars', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('seats', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('no_rooms', models.IntegerField()),
                ('uname', models.CharField(max_length=50)),
            ],
        ),
    ]
