# Generated by Django 3.1.7 on 2021-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAVELAPP', '0002_auto_20210519_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
