# Generated by Django 3.1.7 on 2021-05-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAVELAPP', '0003_auto_20210519_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightinfo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
