# Generated by Django 3.1.7 on 2021-05-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAVELAPP', '0004_auto_20210519_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fconfirm',
            name='bill',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
